_target_: src.physics.dw_eg1.DWForwardEg1
alpha: 1.75
k: 2
lambda_val: 1.0
x_lim: [0, 1]
t_lim: [0, 2]
method: "GJ-II"
monte_carlo_params:
  nums: 50
  eps: 1e-10
gauss_jacobi_params:
  nums: 64
weights:
  domain: 1.0
  boundary: 1.0
  initial: 1.0
  initial_dt: 1.0
